#Experiment 9
### Tools for EDA - Study of Numpy Library

Dhruv Verulkar

25070123162



In [9]:
#Declaration of Numpy
import numpy as np

a=np.array([1,10,20,30.5,40,50,500])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(b)

[  1.   10.   20.   30.5  40.   50.  500. ]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
#Dimension of Array
print(a.ndim)
print(b.ndim)


1
2


In [6]:
#Size of Array
print(a.size)
print(b.size)

7
9


In [7]:
#Shape of Array
print(a.shape)
print(b.shape)

(7,)
(3, 3)


In [10]:
#Data type of Array
print(a.dtype)
print(b.dtype)

float64
int64


In [21]:
#In-built functions using Numpy
#creating a matrix of zeroes
c=np.zeros((2,3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#creating matrix of ones
d=np.ones((2,3))
print(d)


In [16]:
#creating an identical matrix
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
#print numbers from n to n-1 with gaps
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [19]:
#printing form 0 to 1 with 4 equal parts
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [20]:
#multiplying a scalar with matrix
print(b*2)
print(a+5)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[  6.   15.   25.   35.5  45.   55.  505. ]


In [23]:
#Mean of a matrix
print(np.mean(b))
print(np.mean(a))

5.0
93.07142857142857


In [24]:
#median of a matrix
print(np.median(b))
print(np.median(a))

5.0
30.5


In [25]:
#sum of a matrix
print(np.sum(b))
print(np.sum(a))


45
651.5


In [27]:
#max and min of a matrix
print(np.max(b))
print(np.max(a))
print(np.min(b))
print(np.min(a))

9
500.0
1
1.0
